//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// БазДан.
    /// </summary>
    // *** Start programmer edit section *** (БазДан CustomAttributes)

    // *** End programmer edit section *** (БазДан CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БазДанE", new string[] {
            "СпрСтуд as \'Фио Студента\'",
            "СпрСтуд.Фио as \'Фио Студента\'",
            "СпрСтуд.Группа.Наименование as \'Наименование Группы\'",
            "СпрСтуд.Дисциплина.Наименование as \'Наименование Дисциплины\'",
            "Материал as \'Материал\'",
            "Материал.Наименование as \'Наименование Материала\'",
            "Материал.Вид as \'Вид Материала\'"})]
    [MasterViewDefineAttribute("БазДанE", "СпрСтуд", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фио Студента")]
    [MasterViewDefineAttribute("БазДанE", "Материал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование Материала")]
    public class БазДан : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fВремя;
        
        private IIS.Kursovaya_Rabota_2.Материал fМатериал;
        
        private IIS.Kursovaya_Rabota_2.СпрСтуд fСпрСтуд;
        
        private IIS.Kursovaya_Rabota_2.ПрикрепКн fПрикрепКн;
        
        // *** Start programmer edit section *** (БазДан CustomMembers)

        // *** End programmer edit section *** (БазДан CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (БазДан.Время CustomAttributes)

        // *** End programmer edit section *** (БазДан.Время CustomAttributes)
        public virtual System.DateTime Время
        {
            get
            {
                // *** Start programmer edit section *** (БазДан.Время Get start)

                // *** End programmer edit section *** (БазДан.Время Get start)
                System.DateTime result = this.fВремя;
                // *** Start programmer edit section *** (БазДан.Время Get end)

                // *** End programmer edit section *** (БазДан.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазДан.Время Set start)

                // *** End programmer edit section *** (БазДан.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (БазДан.Время Set end)

                // *** End programmer edit section *** (БазДан.Время Set end)
            }
        }
        
        /// <summary>
        /// БазДан.
        /// </summary>
        // *** Start programmer edit section *** (БазДан.Материал CustomAttributes)

        // *** End programmer edit section *** (БазДан.Материал CustomAttributes)
        [PropertyStorage(new string[] {
                "Материал"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_2.Материал Материал
        {
            get
            {
                // *** Start programmer edit section *** (БазДан.Материал Get start)

                // *** End programmer edit section *** (БазДан.Материал Get start)
                IIS.Kursovaya_Rabota_2.Материал result = this.fМатериал;
                // *** Start programmer edit section *** (БазДан.Материал Get end)

                // *** End programmer edit section *** (БазДан.Материал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазДан.Материал Set start)

                // *** End programmer edit section *** (БазДан.Материал Set start)
                this.fМатериал = value;
                // *** Start programmer edit section *** (БазДан.Материал Set end)

                // *** End programmer edit section *** (БазДан.Материал Set end)
            }
        }
        
        /// <summary>
        /// БазДан.
        /// </summary>
        // *** Start programmer edit section *** (БазДан.СпрСтуд CustomAttributes)

        // *** End programmer edit section *** (БазДан.СпрСтуд CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрСтуд"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_2.СпрСтуд СпрСтуд
        {
            get
            {
                // *** Start programmer edit section *** (БазДан.СпрСтуд Get start)

                // *** End programmer edit section *** (БазДан.СпрСтуд Get start)
                IIS.Kursovaya_Rabota_2.СпрСтуд result = this.fСпрСтуд;
                // *** Start programmer edit section *** (БазДан.СпрСтуд Get end)

                // *** End programmer edit section *** (БазДан.СпрСтуд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазДан.СпрСтуд Set start)

                // *** End programmer edit section *** (БазДан.СпрСтуд Set start)
                this.fСпрСтуд = value;
                // *** Start programmer edit section *** (БазДан.СпрСтуд Set end)

                // *** End programmer edit section *** (БазДан.СпрСтуд Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kursovaya_Rabota_2.ПрикрепКн.
        /// </summary>
        // *** Start programmer edit section *** (БазДан.ПрикрепКн CustomAttributes)

        // *** End programmer edit section *** (БазДан.ПрикрепКн CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ПрикрепКн"})]
        public virtual IIS.Kursovaya_Rabota_2.ПрикрепКн ПрикрепКн
        {
            get
            {
                // *** Start programmer edit section *** (БазДан.ПрикрепКн Get start)

                // *** End programmer edit section *** (БазДан.ПрикрепКн Get start)
                IIS.Kursovaya_Rabota_2.ПрикрепКн result = this.fПрикрепКн;
                // *** Start programmer edit section *** (БазДан.ПрикрепКн Get end)

                // *** End programmer edit section *** (БазДан.ПрикрепКн Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (БазДан.ПрикрепКн Set start)

                // *** End programmer edit section *** (БазДан.ПрикрепКн Set start)
                this.fПрикрепКн = value;
                // *** Start programmer edit section *** (БазДан.ПрикрепКн Set end)

                // *** End programmer edit section *** (БазДан.ПрикрепКн Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БазДанE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БазДанE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БазДанE", typeof(IIS.Kursovaya_Rabota_2.БазДан));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of БазДан.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfБазДан CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfБазДан CustomAttributes)
    public class DetailArrayOfБазДан : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kursovaya_Rabota_2.DetailArrayOfБазДан members)

        // *** End programmer edit section *** (IIS.Kursovaya_Rabota_2.DetailArrayOfБазДан members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type БазДан by index.
        /// </summary>
        /// <summary>
        /// Adds object with type БазДан.
        /// </summary>
        public DetailArrayOfБазДан(IIS.Kursovaya_Rabota_2.ПрикрепКн fПрикрепКн) : 
                base(typeof(БазДан), ((ICSSoft.STORMNET.DataObject)(fПрикрепКн)))
        {
        }
        
        public IIS.Kursovaya_Rabota_2.БазДан this[int index]
        {
            get
            {
                return ((IIS.Kursovaya_Rabota_2.БазДан)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kursovaya_Rabota_2.БазДан dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
