//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Группа.
    /// </summary>
    // *** Start programmer edit section *** (Группа CustomAttributes)

    // *** End programmer edit section *** (Группа CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГруппаE", new string[] {
            "Наименование as \'Наименование Группы\'"})]
    [View("ГруппаL", new string[] {
            "Наименование as \'Наименование Группы\'"})]
    public class Группа : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Группа CustomMembers)

        // *** End programmer edit section *** (Группа CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Группа.Наименование CustomAttributes)

        // *** End programmer edit section *** (Группа.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Группа.Наименование Get start)

                // *** End programmer edit section *** (Группа.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Группа.Наименование Get end)

                // *** End programmer edit section *** (Группа.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Группа.Наименование Set start)

                // *** End programmer edit section *** (Группа.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Группа.Наименование Set end)

                // *** End programmer edit section *** (Группа.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГруппаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГруппаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГруппаE", typeof(IIS.Kursovaya_Rabota_2.Группа));
                }
            }
            
            /// <summary>
            /// "ГруппаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГруппаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГруппаL", typeof(IIS.Kursovaya_Rabota_2.Группа));
                }
            }
        }
    }
}
