//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Дисциплина.
    /// </summary>
    // *** Start programmer edit section *** (Дисциплина CustomAttributes)

    // *** End programmer edit section *** (Дисциплина CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДисциплинаE", new string[] {
            "Наименование as \'Наименование Дисциплины\'"})]
    [View("ДисциплинаL", new string[] {
            "Наименование as \'Наименование Дисциплины\'"})]
    public class Дисциплина : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Дисциплина CustomMembers)

        // *** End programmer edit section *** (Дисциплина CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Дисциплина.Наименование CustomAttributes)

        // *** End programmer edit section *** (Дисциплина.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Дисциплина.Наименование Get start)

                // *** End programmer edit section *** (Дисциплина.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Дисциплина.Наименование Get end)

                // *** End programmer edit section *** (Дисциплина.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Дисциплина.Наименование Set start)

                // *** End programmer edit section *** (Дисциплина.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Дисциплина.Наименование Set end)

                // *** End programmer edit section *** (Дисциплина.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДисциплинаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДисциплинаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДисциплинаE", typeof(IIS.Kursovaya_Rabota_2.Дисциплина));
                }
            }
            
            /// <summary>
            /// "ДисциплинаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДисциплинаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДисциплинаL", typeof(IIS.Kursovaya_Rabota_2.Дисциплина));
                }
            }
        }
    }
}
