//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ПрикрепКн.
    /// </summary>
    // *** Start programmer edit section *** (ПрикрепКн CustomAttributes)

    // *** End programmer edit section *** (ПрикрепКн CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПрикрепКнE", new string[] {
            "СпрСотр as \'Фио Сотрудника\'",
            "СпрСотр.Фио as \'Фио Сотрудника\'",
            "СпрСотр.Группа.Наименование as \'Наименование Группы\'",
            "СпрСотр.Дисциплина.Наименование as \'Наименование Дисциплины\'"})]
    [AssociatedDetailViewAttribute("ПрикрепКнE", "БазДан", "БазДанE", true, "", "База Данных", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ПрикрепКнE", "СпрСотр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фио Сотрудника")]
    [View("ПрикрепКнL", new string[] {
            "СпрСотр.Фио as \' Фио Сотрудника\'",
            "СпрСотр.Группа.Наименование as \'Наименование Группы\'",
            "СпрСотр.Дисциплина.Наименование as \'Наименование Дисциплины\'"})]
    public class ПрикрепКн : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Kursovaya_Rabota_2.СпрСотр fСпрСотр;
        
        private IIS.Kursovaya_Rabota_2.DetailArrayOfБазДан fБазДан;
        
        // *** Start programmer edit section *** (ПрикрепКн CustomMembers)

        // *** End programmer edit section *** (ПрикрепКн CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ПрикрепКн.Дата CustomAttributes)

        // *** End programmer edit section *** (ПрикрепКн.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ПрикрепКн.Дата Get start)

                // *** End programmer edit section *** (ПрикрепКн.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ПрикрепКн.Дата Get end)

                // *** End programmer edit section *** (ПрикрепКн.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПрикрепКн.Дата Set start)

                // *** End programmer edit section *** (ПрикрепКн.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ПрикрепКн.Дата Set end)

                // *** End programmer edit section *** (ПрикрепКн.Дата Set end)
            }
        }
        
        /// <summary>
        /// ПрикрепКн.
        /// </summary>
        // *** Start programmer edit section *** (ПрикрепКн.СпрСотр CustomAttributes)

        // *** End programmer edit section *** (ПрикрепКн.СпрСотр CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрСотр"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_2.СпрСотр СпрСотр
        {
            get
            {
                // *** Start programmer edit section *** (ПрикрепКн.СпрСотр Get start)

                // *** End programmer edit section *** (ПрикрепКн.СпрСотр Get start)
                IIS.Kursovaya_Rabota_2.СпрСотр result = this.fСпрСотр;
                // *** Start programmer edit section *** (ПрикрепКн.СпрСотр Get end)

                // *** End programmer edit section *** (ПрикрепКн.СпрСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПрикрепКн.СпрСотр Set start)

                // *** End programmer edit section *** (ПрикрепКн.СпрСотр Set start)
                this.fСпрСотр = value;
                // *** Start programmer edit section *** (ПрикрепКн.СпрСотр Set end)

                // *** End programmer edit section *** (ПрикрепКн.СпрСотр Set end)
            }
        }
        
        /// <summary>
        /// ПрикрепКн.
        /// </summary>
        // *** Start programmer edit section *** (ПрикрепКн.БазДан CustomAttributes)

        // *** End programmer edit section *** (ПрикрепКн.БазДан CustomAttributes)
        public virtual IIS.Kursovaya_Rabota_2.DetailArrayOfБазДан БазДан
        {
            get
            {
                // *** Start programmer edit section *** (ПрикрепКн.БазДан Get start)

                // *** End programmer edit section *** (ПрикрепКн.БазДан Get start)
                if ((this.fБазДан == null))
                {
                    this.fБазДан = new IIS.Kursovaya_Rabota_2.DetailArrayOfБазДан(this);
                }
                IIS.Kursovaya_Rabota_2.DetailArrayOfБазДан result = this.fБазДан;
                // *** Start programmer edit section *** (ПрикрепКн.БазДан Get end)

                // *** End programmer edit section *** (ПрикрепКн.БазДан Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПрикрепКн.БазДан Set start)

                // *** End programmer edit section *** (ПрикрепКн.БазДан Set start)
                this.fБазДан = value;
                // *** Start programmer edit section *** (ПрикрепКн.БазДан Set end)

                // *** End programmer edit section *** (ПрикрепКн.БазДан Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПрикрепКнE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрикрепКнE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрикрепКнE", typeof(IIS.Kursovaya_Rabota_2.ПрикрепКн));
                }
            }
            
            /// <summary>
            /// "ПрикрепКнL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрикрепКнL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрикрепКнL", typeof(IIS.Kursovaya_Rabota_2.ПрикрепКн));
                }
            }
        }
    }
}
