//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Прикрепление.
    /// </summary>
    // *** Start programmer edit section *** (Прикрепление CustomAttributes)

    // *** End programmer edit section *** (Прикрепление CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПрикреплениеE", new string[] {
            "СпрСотр as \'Фио Сотрудника\'",
            "СпрСотр.Фио as \'Фио Сотрудника\'",
            "СпрСотр.Группа.Наименование as \'Наименование Группы\'",
            "СпрСотр.Дисциплина.Наименование as \'Наименование Дисциплины\'"})]
    [MasterViewDefineAttribute("ПрикреплениеE", "СпрСотр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фио Сотрудника")]
    [View("ПрикреплениеL", new string[] {
            "СпрСотр.Фио as \'Фио Сотрудника\'",
            "СпрСотр.Группа.Наименование as \'Наименование Группы\'",
            "СпрСотр.Дисциплина as \'Наименование Дисциплины\'"})]
    public class Прикрепление : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Kursovaya_Rabota_2.СпрСотр fСпрСотр;
        
        // *** Start programmer edit section *** (Прикрепление CustomMembers)

        // *** End programmer edit section *** (Прикрепление CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Прикрепление.Дата CustomAttributes)

        // *** End programmer edit section *** (Прикрепление.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Прикрепление.Дата Get start)

                // *** End programmer edit section *** (Прикрепление.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Прикрепление.Дата Get end)

                // *** End programmer edit section *** (Прикрепление.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Прикрепление.Дата Set start)

                // *** End programmer edit section *** (Прикрепление.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Прикрепление.Дата Set end)

                // *** End programmer edit section *** (Прикрепление.Дата Set end)
            }
        }
        
        /// <summary>
        /// Прикрепление.
        /// </summary>
        // *** Start programmer edit section *** (Прикрепление.СпрСотр CustomAttributes)

        // *** End programmer edit section *** (Прикрепление.СпрСотр CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрСотр"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_2.СпрСотр СпрСотр
        {
            get
            {
                // *** Start programmer edit section *** (Прикрепление.СпрСотр Get start)

                // *** End programmer edit section *** (Прикрепление.СпрСотр Get start)
                IIS.Kursovaya_Rabota_2.СпрСотр result = this.fСпрСотр;
                // *** Start programmer edit section *** (Прикрепление.СпрСотр Get end)

                // *** End programmer edit section *** (Прикрепление.СпрСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Прикрепление.СпрСотр Set start)

                // *** End programmer edit section *** (Прикрепление.СпрСотр Set start)
                this.fСпрСотр = value;
                // *** Start programmer edit section *** (Прикрепление.СпрСотр Set end)

                // *** End programmer edit section *** (Прикрепление.СпрСотр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПрикреплениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрикреплениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрикреплениеE", typeof(IIS.Kursovaya_Rabota_2.Прикрепление));
                }
            }
            
            /// <summary>
            /// "ПрикреплениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрикреплениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрикреплениеL", typeof(IIS.Kursovaya_Rabota_2.Прикрепление));
                }
            }
        }
    }
}
