//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Rabota_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СпрСтуд.
    /// </summary>
    // *** Start programmer edit section *** (СпрСтуд CustomAttributes)

    // *** End programmer edit section *** (СпрСтуд CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпрСтудE", new string[] {
            "Фио as \'Фио Студента\'",
            "Группа as \'Наименование Группы\'",
            "Группа.Наименование as \'Наименование Группы\'",
            "Дисциплина as \'Наименование Дисциплины \'",
            "Дисциплина.Наименование as \'Наименование Дисциплины \'"})]
    [View("СпрСтудL", new string[] {
            "Фио as \'Фио Студента\'",
            "Группа.Наименование as \'Наименование Группы\'",
            "Дисциплина.Наименование as \'Наименование Дисциплины\'"})]
    public class СпрСтуд : ICSSoft.STORMNET.DataObject
    {
        
        private string fФио;
        
        private IIS.Kursovaya_Rabota_2.Группа fГруппа;
        
        private IIS.Kursovaya_Rabota_2.Дисциплина fДисциплина;
        
        // *** Start programmer edit section *** (СпрСтуд CustomMembers)

        // *** End programmer edit section *** (СпрСтуд CustomMembers)

        
        /// <summary>
        /// Фио.
        /// </summary>
        // *** Start programmer edit section *** (СпрСтуд.Фио CustomAttributes)

        // *** End programmer edit section *** (СпрСтуд.Фио CustomAttributes)
        [StrLen(255)]
        public virtual string Фио
        {
            get
            {
                // *** Start programmer edit section *** (СпрСтуд.Фио Get start)

                // *** End programmer edit section *** (СпрСтуд.Фио Get start)
                string result = this.fФио;
                // *** Start programmer edit section *** (СпрСтуд.Фио Get end)

                // *** End programmer edit section *** (СпрСтуд.Фио Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрСтуд.Фио Set start)

                // *** End programmer edit section *** (СпрСтуд.Фио Set start)
                this.fФио = value;
                // *** Start programmer edit section *** (СпрСтуд.Фио Set end)

                // *** End programmer edit section *** (СпрСтуд.Фио Set end)
            }
        }
        
        /// <summary>
        /// СпрСтуд.
        /// </summary>
        // *** Start programmer edit section *** (СпрСтуд.Группа CustomAttributes)

        // *** End programmer edit section *** (СпрСтуд.Группа CustomAttributes)
        [PropertyStorage(new string[] {
                "Группа"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_2.Группа Группа
        {
            get
            {
                // *** Start programmer edit section *** (СпрСтуд.Группа Get start)

                // *** End programmer edit section *** (СпрСтуд.Группа Get start)
                IIS.Kursovaya_Rabota_2.Группа result = this.fГруппа;
                // *** Start programmer edit section *** (СпрСтуд.Группа Get end)

                // *** End programmer edit section *** (СпрСтуд.Группа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрСтуд.Группа Set start)

                // *** End programmer edit section *** (СпрСтуд.Группа Set start)
                this.fГруппа = value;
                // *** Start programmer edit section *** (СпрСтуд.Группа Set end)

                // *** End programmer edit section *** (СпрСтуд.Группа Set end)
            }
        }
        
        /// <summary>
        /// СпрСтуд.
        /// </summary>
        // *** Start programmer edit section *** (СпрСтуд.Дисциплина CustomAttributes)

        // *** End programmer edit section *** (СпрСтуд.Дисциплина CustomAttributes)
        [PropertyStorage(new string[] {
                "Дисциплина"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Rabota_2.Дисциплина Дисциплина
        {
            get
            {
                // *** Start programmer edit section *** (СпрСтуд.Дисциплина Get start)

                // *** End programmer edit section *** (СпрСтуд.Дисциплина Get start)
                IIS.Kursovaya_Rabota_2.Дисциплина result = this.fДисциплина;
                // *** Start programmer edit section *** (СпрСтуд.Дисциплина Get end)

                // *** End programmer edit section *** (СпрСтуд.Дисциплина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрСтуд.Дисциплина Set start)

                // *** End programmer edit section *** (СпрСтуд.Дисциплина Set start)
                this.fДисциплина = value;
                // *** Start programmer edit section *** (СпрСтуд.Дисциплина Set end)

                // *** End programmer edit section *** (СпрСтуд.Дисциплина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпрСтудE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрСтудE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрСтудE", typeof(IIS.Kursovaya_Rabota_2.СпрСтуд));
                }
            }
            
            /// <summary>
            /// "СпрСтудL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрСтудL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрСтудL", typeof(IIS.Kursovaya_Rabota_2.СпрСтуд));
                }
            }
        }
    }
}
